name: supreme-robot
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python>=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - scikit-learn

  - pip:
    - keras-core
    - jax[cpu]

  # linting
  - black
  - isort