name: supreme-robot
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - yfinance
  - matplotlib
  - scikit-learn
  - catboost
  - ipywidgets

  # linting
  - black
  - flake8
  - isort